name: 'Setup Cargo Auditable for wash builds'
description: |
  Configures a rust toolchain with cargo-auditable for use in building
  WebAssembly components with wash and creating an auditable SBOM.

  wash CLI must be installed and available in PATH. We recommend using the
  wasmcloud/setup-wash-action prior to this action to install wash.

outputs:
  component_path:
    description: 'Path to the built WebAssembly component'
    value: ${{ steps.build.outputs.component_path }}

runs:
  using: 'composite'
  steps:
    - uses: taiki-e/install-action@4575ae687efd0e2c78240087f26013fb2484987f # v2.62.6
      if: ${{ inputs.attestation == 'true' }}
      with:
        tool: cargo-auditable,cargo-audit

    - name: Set auditable as custom build command in .wash/config.json
      shell: bash
      run: |
        mkdir -p .wash
        
        # Create or update config with jq, merging with existing config
        if [ -f .wash/config.json ]; then
          # Merge with existing config, ensuring nested objects exist
          jq '(.build // {}) as $build | 
              (.build.rust // {}) as $rust |
              .build = ($build | .rust = ($rust | 
                .custom_command = "cargo auditable build --release --target wasm32-wasip2" |
              ))' .wash/config.json > .wash/config.json.tmp
          mv .wash/config.json.tmp .wash/config.json
        else
          # Create new config
          jq -n '{
            "build": {
              "rust": {
                "custom_command": "cargo auditable build --release --target wasm32-wasip2"
              }
            }
          }' > .wash/config.json
        fi
